Repository airicbear/cis-4496-project, pull requests merged in 2023-04, with the labels that each got.

#100 Add author's monet2ukiyoe
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/components/Model2ModelCard.tsx
  Code/cyclegan_website/pages/generators/monet2ukiyoe.tsx
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/utils/drawOnnxPrediction.ts
  Code/cyclegan_website/utils/imageToDataUri.ts
Labels: enhancement

#101 Fix typo
  Code/cyclegan_website/pages/generators/monet2ukiyoe.tsx
Labels: bug

#102 Add our Monet2Ukiyoe
  Code/cyclegan_website/components/Model2ModelCard.tsx
  Code/cyclegan_website/pages/generators/monet2ukiyoe.tsx
  Code/cyclegan_website/utils/drawTfjsPrediction.ts
Labels: enhancement

#104 Add Bimonthly Progress Report 2
  Docs/Project/Bimonthly Progress Report 2.md
  Docs/Project/Images/bad_example_authors.png
  Docs/Project/Images/bad_example_ours.png
  Docs/Project/Images/bad_example_photo.png
  Docs/Project/Images/epochs_vs_fid.png
  Docs/Project/Images/epochs_vs_mifid_improved.png
  Docs/Project/Images/good_example_authors.jpg
  Docs/Project/Images/good_example_ours.jpg
  Docs/Project/Images/good_example_photo.jpg
  Docs/Project/Images/photo2monet_rgb_distribution_improved.png
Labels: documentation

#105 Fix image links and reference formatting
  Docs/Project/Bimonthly Progress Report 2.md
Labels: documentation

#106 Update Bimonthly Progress Report 2.md
  Docs/Project/Bimonthly Progress Report 2.md
Labels: documentation

#107 Update Bimonthly Progress Report 1.md
  Docs/Project/Bimonthly Progress Report 1.md
Labels: documentation

#108 Improve UI responsiveness
  Code/cyclegan_website/components/CanvasOutput.tsx
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/components/ImageInputLabel.tsx
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/styles/globals.css
Labels: enhancement

#109 Add x-axis, y-axis labels and fill area under RGB plot
  Code/cyclegan_website/pages/utilities/plot_rgb_distribution.tsx
Labels: enhancement

#110 Refactor RGB distribution calculation
  Code/cyclegan_website/pages/utilities/plot_rgb_distribution.tsx
  Code/cyclegan_website/utils/getRGB.ts
Labels: refactor

#111 Refactor RGB plotting into separate files
  Code/cyclegan_website/pages/utilities/plot_rgb_distribution.tsx
  Code/cyclegan_website/utils/createPlot.ts
  Code/cyclegan_website/utils/getRGB.ts
  Code/cyclegan_website/utils/plotRGB.ts
Labels: refactor

#112 Add brightness option to RGB plot
  Code/monet_cyclegan/data_acquisition/rgb_distribution.py
  Code/monet_cyclegan/scripts/plot_rgb_distribution.py
Labels: enhancement

#114 Update Data Report.md
  Docs/Data_Report/Data Report.md
Labels: documentation

#115 Plot RGB distribution for images of any size
  Code/monet_cyclegan/data_acquisition/augment.py
  Code/monet_cyclegan/data_acquisition/rgb_distribution.py
  Code/monet_cyclegan/data_acquisition/train_test_split.py
  Code/monet_cyclegan/deployment/generate_images.py
  Code/monet_cyclegan/utils.py
Labels: enhancement

#117 Accept all image types
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/pages/utilities/plot_rgb_distribution.tsx
Labels: enhancement

#118 Add Model and Performance Report
  Docs/Model/Model and Performance Report.md
  Docs/Project/Images/epoch_fid_cezanne.jpg
  Docs/Project/Images/epoch_fid_monet.jpg
  Docs/Project/Images/epoch_fid_ukiyoe.jpg
  Docs/Project/Images/epoch_fid_vangogh.jpg
  Docs/Project/Images/value_function.jpg
Labels: documentation

#119 Update home page UI
  Code/cyclegan_website/components/CardLink.tsx
  Code/cyclegan_website/components/GeneratorCardLinkGrid.tsx
  Code/cyclegan_website/consts/painting2PaintingList.ts
  Code/cyclegan_website/consts/painting2PhotoList.ts
  Code/cyclegan_website/consts/photo2PaintingList.ts
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/public/assets/images/Cezanne2Monet.png
  Code/cyclegan_website/public/assets/images/Cezanne2Photo.png
  Code/cyclegan_website/public/assets/images/Cezanne2Ukiyoe.png
  Code/cyclegan_website/public/assets/images/Cezanne2Vangogh.png
  Code/cyclegan_website/public/assets/images/Monet2Cezanne.png
  Code/cyclegan_website/public/assets/images/Monet2Photo.png
  Code/cyclegan_website/public/assets/images/Monet2Ukiyoe.png
  Code/cyclegan_website/public/assets/images/Monet2Vangogh.png
  Code/cyclegan_website/public/assets/images/Photo2Cezanne.png
  Code/cyclegan_website/public/assets/images/Photo2Monet.png
  Code/cyclegan_website/public/assets/images/Photo2Ukiyoe.png
  Code/cyclegan_website/public/assets/images/Photo2Vangogh.png
  Code/cyclegan_website/public/assets/images/RGB.png
  Code/cyclegan_website/public/assets/images/Ukiyoe2Cezanne.png
  Code/cyclegan_website/public/assets/images/Ukiyoe2Monet.png
  Code/cyclegan_website/public/assets/images/Ukiyoe2Photo.png
  Code/cyclegan_website/public/assets/images/Ukiyoe2Vangogh.png
  Code/cyclegan_website/public/assets/images/Vangogh2Cezanne.png
  Code/cyclegan_website/public/assets/images/Vangogh2Monet.png
  Code/cyclegan_website/public/assets/images/Vangogh2Photo.png
  Code/cyclegan_website/public/assets/images/Vangogh2Ukiyoe.png
Labels: enhancement

#120 Add updated competition models to website
  Code/cyclegan_website/pages/generators/monet2photo.tsx
  Code/cyclegan_website/pages/generators/photo2monet.tsx
Labels: enhancement

#121 Update READMEs
  Code/README.md
  Docs/Data_Report/README.md
  Docs/Model/README.md
  Docs/Project/README.md
  Docs/README.md
Labels: documentation

#122 Added image input info popup
  Code/cyclegan_website/components/ImageInputTitle.tsx
  Code/cyclegan_website/components/InfoIcon.tsx
  Code/cyclegan_website/components/Model2ModelCard.tsx
  Code/cyclegan_website/components/ModelCard.tsx
  Code/cyclegan_website/pages/utilities/plot_rgb_distribution.tsx
Labels: enhancement

#123 Use ORT models
  Code/cyclegan_website/pages/generators/monet2photo.tsx
  Code/cyclegan_website/pages/generators/photo2cezanne.tsx
  Code/cyclegan_website/pages/generators/photo2monet.tsx
  Code/cyclegan_website/pages/generators/photo2ukiyoe.tsx
  Code/cyclegan_website/pages/generators/photo2vangogh.tsx
Labels: enhancement

#124 Fix warning invalid DOM property "fill-rule"
  Code/cyclegan_website/components/InfoIcon.tsx
Labels: bug

#125 Refactor imports
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/utils/createPlot.ts
  Code/cyclegan_website/utils/drawOnnxPrediction.ts
  Code/cyclegan_website/utils/drawTfjsPrediction.ts
  Code/cyclegan_website/utils/plotRGB.ts
Labels: refactor

#126 Use strict typing
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/pages/utilities/plot_rgb_distribution.tsx
  Code/cyclegan_website/tsconfig.json
  Code/cyclegan_website/utils/createPlot.ts
  Code/cyclegan_website/utils/drawOnnxPrediction.ts
  Code/cyclegan_website/utils/drawTfjsPrediction.ts
Labels: enhancement

#127 More strict typing
  Code/cyclegan_website/components/AppHeader.tsx
  Code/cyclegan_website/components/CanvasOutput.tsx
  Code/cyclegan_website/components/CardLink.tsx
  Code/cyclegan_website/components/GeneratorCardLinkGrid.tsx
  Code/cyclegan_website/components/GitHubIcon.tsx
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/components/ImageInputLabel.tsx
  Code/cyclegan_website/components/InfoIcon.tsx
  Code/cyclegan_website/components/Model2ModelCard.tsx
  Code/cyclegan_website/components/ModelCard.tsx
  Code/cyclegan_website/components/MoonIcon.tsx
  Code/cyclegan_website/components/SunIcon.tsx
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/pages/utilities/plot_rgb_distribution.tsx
  Code/cyclegan_website/utils/getRGB.ts
  Code/cyclegan_website/utils/imageToDataUri.ts
Labels: refactor

#128 Remove console logging
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/components/Model2ModelCard.tsx
  Code/cyclegan_website/utils/drawOnnxPrediction.ts
  Code/cyclegan_website/utils/drawTfjsPrediction.ts
  Code/cyclegan_website/utils/getRGB.ts
  Code/cyclegan_website/utils/plotRGB.ts
Labels: refactor

#129 Added Final Presentation
  Docs/Model/Final/4496_Demo_3_V1.pptx.pdf
Labels: documentation

#131 Add Monet test and train data set pages
  Code/cyclegan_website/components/DatasetGrid.tsx
  Code/cyclegan_website/consts/monetTestData.ts
  Code/cyclegan_website/consts/monetTrainData.ts
  Code/cyclegan_website/pages/datasets/monet/test.tsx
  Code/cyclegan_website/pages/datasets/monet/train.tsx
  Code/cyclegan_website/pages/index.tsx
Labels: enhancement

#132 Add photo data set pages
  Code/cyclegan_website/consts/photoTestData.ts
  Code/cyclegan_website/consts/photoTrainData.ts
  Code/cyclegan_website/pages/datasets/photo/test.tsx
  Code/cyclegan_website/pages/datasets/photo/train.tsx
  Code/cyclegan_website/pages/index.tsx
Labels: enhancement

#133 Add Ukiyoe data set pages
  Code/cyclegan_website/consts/ukiyoeTestData.ts
  Code/cyclegan_website/consts/ukiyoeTrainData.ts
  Code/cyclegan_website/pages/datasets/ukiyoe/test.tsx
  Code/cyclegan_website/pages/datasets/ukiyoe/train.tsx
  Code/cyclegan_website/pages/index.tsx
Labels: enhancement

#134 Add Cezanne data set pages
  Code/cyclegan_website/consts/cezanneTestData.ts
  Code/cyclegan_website/consts/cezanneTrainData.ts
  Code/cyclegan_website/pages/datasets/cezanne/test.tsx
  Code/cyclegan_website/pages/datasets/cezanne/train.tsx
  Code/cyclegan_website/pages/index.tsx
Labels: enhancement

#135 Add Van Gogh data set page
  Code/cyclegan_website/consts/vangoghTestTrainData.ts
  Code/cyclegan_website/pages/datasets/vangogh/test-train.tsx
  Code/cyclegan_website/pages/index.tsx
Labels: enhancement

#136 Rename competition model from "generic" to "general"
  Code/cyclegan_website/pages/generators/monet2photo.tsx
  Code/cyclegan_website/pages/generators/photo2monet.tsx
Labels: enhancement

#137 Add test photo to Monet page
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/pages/predictions/photo/test/monet.tsx
Labels: enhancement

#138 Change title to "Test Photo to Monet Predictions"
  Code/cyclegan_website/pages/predictions/photo/test/monet.tsx
Labels: enhancement

#139 Refactor image generation to allow for painting2photo
  Code/monet_cyclegan/deployment/generate_images.py
  Code/monet_cyclegan/modeling/predict.py
  Code/monet_cyclegan/scripts/generate_images.py
Labels: refactor

#141 Add author's Monet to photo page
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/pages/predictions/monet/test/photo/authors.tsx
  Code/cyclegan_website/pages/predictions/monet/test/photo/ours/competition/final.tsx
  Code/cyclegan_website/pages/predictions/photo/test/monet/ours/competition/final.tsx
Labels: enhancement

#142 Add augment image page
  Code/cyclegan_website/components/CanvasOutput.tsx
  Code/cyclegan_website/components/Model2ModelCard.tsx
  Code/cyclegan_website/components/ModelCard.tsx
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/pages/utilities/augment_image.tsx
  Code/cyclegan_website/public/assets/images/AugmentImage.jpg
Labels: enhancement

#144 Add our Monet to photo (general) page
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/pages/predictions/monet/test/photo/authors.tsx
  Code/cyclegan_website/pages/predictions/monet/test/photo/ours/competition/final.tsx
  Code/cyclegan_website/pages/predictions/monet/test/photo/ours/general.tsx
  Code/cyclegan_website/pages/predictions/photo/test/monet/authors.tsx
  Code/cyclegan_website/pages/predictions/photo/test/monet/ours/competition/final.tsx
Labels: enhancement

#145 Add our photo to Monet (general) page
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/pages/predictions/photo/test/monet/ours/general.tsx
Labels: enhancement

#146 Add author's photo to Ukiyoe page
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/pages/predictions/photo/test/ukiyoe/authors.tsx
Labels: enhancement

#147 Add our photo to Ukiyoe page
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/pages/predictions/photo/test/ukiyoe/ours.tsx
Labels: enhancement

#148 Add our photo to Cezanne page
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/pages/predictions/photo/test/cezanne/ours.tsx
Labels: enhancement

#149 Add our photo to Van Gogh page
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/pages/predictions/photo/test/vangogh/ours.tsx
Labels: enhancement
