Repository airicbear/cis-4496-project, pull requests merged in 2023-03, with the labels that each got.

#57 Add website functionality
  Code/cyclegan_website/.gitignore
  Code/cyclegan_website/components/AppHeader.tsx
  Code/cyclegan_website/components/GitHubIcon.tsx
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/components/ModelCard.tsx
  Code/cyclegan_website/components/MoonIcon.tsx
  Code/cyclegan_website/components/SunIcon.tsx
  Code/cyclegan_website/next-env.d.ts
  Code/cyclegan_website/package-lock.json
  Code/cyclegan_website/package.json
  Code/cyclegan_website/pages/_app.tsx
  Code/cyclegan_website/pages/index.js
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/styles/Home.module.css
  Code/cyclegan_website/styles/globals.css
  Code/cyclegan_website/tsconfig.json
  Code/monet_cyclegan/consts.py
  Code/monet_cyclegan/deployment/load_model.py
  Code/monet_cyclegan/environment-macos.yaml
  Code/monet_cyclegan/modeling/discriminator.py
  Code/monet_cyclegan/modeling/generator.py
  Code/monet_cyclegan/modeling/layers.py
  Code/monet_cyclegan/modeling/train.py
  Code/monet_cyclegan/scripts/__init__.py
  Code/monet_cyclegan/scripts/calculate_fid.py
  Code/monet_cyclegan/scripts/generate_images.py
  Code/monet_cyclegan/scripts/save_tfjs_weights.py
  Code/monet_cyclegan/scripts/train.py
Labels: enhancement

#62 Fix load model
  Code/monet_cyclegan/deployment/load_model.py
Labels: bug

#64 Add convert_to_tfrec script
  Code/monet_cyclegan/scripts/convert_to_tfrec.py
Labels: enhancement

#65 Resize input image
  Code/cyclegan_website/components/ImageInput.tsx
Labels: enhancement

#66 Add logs to visualize model losses in TensorBoard
  Code/monet_cyclegan/modeling/discriminator.py
  Code/monet_cyclegan/modeling/generator.py
  Code/monet_cyclegan/modeling/losses.py
  Code/monet_cyclegan/modeling/model.py
  Code/monet_cyclegan/modeling/train.py
  Code/monet_cyclegan/scripts/train.py
Labels: enhancement

#67 Revert TensorBoard changes
  Code/monet_cyclegan/modeling/model.py
  Code/monet_cyclegan/modeling/train.py
  Code/monet_cyclegan/scripts/train.py
Labels: refactor

#68 Remove TensorBoard callback from train_model
  Code/monet_cyclegan/modeling/train.py
Labels: refactor

#69 Add ONNX model support to the website
  Code/cyclegan_website/.gitignore
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/components/ModelCard.tsx
  Code/cyclegan_website/next.config.js
  Code/cyclegan_website/package-lock.json
  Code/cyclegan_website/package.json
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/utils/drawOnnxPrediction.ts
  Code/cyclegan_website/utils/drawTfjsPrediction.ts
Labels: enhancement

#71 Fix TFREC image color encoding
  Code/monet_cyclegan/utils.py
Labels: bug

#72 Add save TFREC to JPG script
  Code/monet_cyclegan/scripts/save_tfrec_to_jpg.py
  Code/monet_cyclegan/utils.py
Labels: enhancement

#74 Load ONNX inference session when website loads
  .gitignore
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/utils/drawOnnxPrediction.ts
  Code/cyclegan_website/utils/drawTfjsPrediction.ts
Labels: enhancement

#76 Set input image background size to 100%
  Code/cyclegan_website/components/ImageInput.tsx
Labels: enhancement

#77 Save TensorFlow.js model to IndexedDB
  Code/cyclegan_website/components/ImageInput.tsx
Labels: enhancement

#78 Add loading indicator for model inferencing
  Code/cyclegan_website/components/CanvasOutput.tsx
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/components/ModelCard.tsx
Labels: enhancement

#79 Handle getTfjsModel rejection
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/utils/drawOnnxPrediction.ts
Labels: bug

#80 Set num arg default to -1
  Code/monet_cyclegan/scripts/save_tfrec_to_jpg.py
  Code/monet_cyclegan/utils.py
Labels: bug

#81 Update README.md
  Code/monet_cyclegan/deployment/README.md
Labels: documentation

#89 Update Website README
  .gitignore
  Code/cyclegan_website/README.md
  Code/cyclegan_website/next-env.d.ts
  Code/cyclegan_website/screenshots/photo2monet.png
Labels: documentation

#91 Add more models
  Code/cyclegan_website/.gitignore
  Code/cyclegan_website/components/AppHeader.tsx
  Code/cyclegan_website/components/ModelCard.tsx
  Code/cyclegan_website/next.config.js
  Code/cyclegan_website/pages/generators/monet2photo.tsx
  Code/cyclegan_website/pages/generators/photo2cezanne.tsx
  Code/cyclegan_website/pages/generators/photo2monet.tsx
  Code/cyclegan_website/pages/generators/photo2ukiyoe.tsx
  Code/cyclegan_website/pages/generators/photo2vangogh.tsx
  Code/cyclegan_website/pages/generators/ukiyoe2photo.tsx
  Code/cyclegan_website/pages/index.tsx
Labels: enhancement

#92 Add download button on output hover
  Code/cyclegan_website/components/CanvasOutput.tsx
  Code/cyclegan_website/components/ModelCard.tsx
  Code/cyclegan_website/package-lock.json
  Code/cyclegan_website/package.json
Labels: enhancement

#93 Add Vercel audience analytics
  Code/cyclegan_website/package-lock.json
  Code/cyclegan_website/package.json
  Code/cyclegan_website/pages/_app.tsx
Labels: enhancement

#94 Website
  Code/cyclegan_website/components/CanvasOutput.tsx
  Code/cyclegan_website/components/ImageInput.tsx
  Code/cyclegan_website/components/ImageInputLabel.tsx
  Code/cyclegan_website/components/ModelCard.tsx
  Code/cyclegan_website/utils/initializeLabel.ts
Labels: refactor

#95 Add plot RGB distribution page
  Code/cyclegan_website/.gitignore
  Code/cyclegan_website/components/ImageInputLabel.tsx
  Code/cyclegan_website/package-lock.json
  Code/cyclegan_website/package.json
  Code/cyclegan_website/pages/index.tsx
  Code/cyclegan_website/pages/utilities/plot_rgb_distribution.tsx
Labels: enhancement

#96 Add website link to README
  README.md
Labels: documentation

#98 Update README.md
  Docs/Model/README.md
Labels: documentation
